service: zhishidianExpress
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-2
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true